name: "💡 Suggest an Enhancement"
description: "Propose a new feature or an improvement to the platform."
labels: ["Improvement"]
body:
  - type: textarea
    id: problem-statement
    attributes:
      label: "What problem would this enhancement solve?"
      description: "e.g., 'It's currently difficult to do X, which wastes time.'"
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: "Describe your proposed solution"
      description: "How do you envision this new feature or improvement working?"
    validations:
      required: true
